<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260326163418 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE employee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, surname VARCHAR(100) NOT NULL, personal_identity_number VARCHAR(12) NOT NULL, gender VARCHAR(10) NOT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(100) NOT NULL, address_country_code VARCHAR(2) NOT NULL, address_city VARCHAR(100) NOT NULL, address_street VARCHAR(100) NOT NULL, address_street_number VARCHAR(10) NOT NULL, address_postal_code VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE employee');
    }
}
